name: ldlg
channels:
  - conda-forge # Make sure conda-forge is listed first
  - defaults
dependencies:
  - python=3.8
  - pip
  - pyyaml=6.0   # Keep this from the previous step
  - tokenizers=0.12.1 # Add tokenizers
  - grpcio=1.49.1   # Add grpcio